services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'sleep 3 && npm start'
    volumes:
      - "./app:/app"
    ports: 
      - "8000:8080"

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "app"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: