version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password

  app:
    depends_on:
      - "db"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
    build:
      context: .
      dockerfile: Dockerfile.production
    image: "pochka15/devops-for-programmers-project-74"
    command: bash -c 'sleep 3 && npm test'
    ports: 
      - "8000:3000"
