version: "3.7"
services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD

  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.production
    image: "pochka15/devops-for-programmers-project-74"
    command: bash -c "sleep 3 && npm test"
    environment:
      - DATABASE_NAME
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - DATABASE_PORT
      - DATABASE_HOST
