version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password

  app:
    depends_on:
      - "db"
    build:
      context: .
      dockerfile: Dockerfile.production
    image: "pochka15/devops-for-programmers-project-74"
    command: npm test
    ports: 
      - "8000:3000"
