name: push

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  push-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run CI
        run: make ci
